might need .add_development_dependency after all
  $ bundle exec rake spec
  rake aborted!
  LoadError: cannot load such file -- rspec/core
  /home/travis/build/alexdean/app_status/Rakefile:14:in `require'

https://travis-ci.org/alexdean/app_status/jobs/549798281